##################mysql??##################
mallchat.mysql.ip=127.0.0.1
mallchat.mysql.port=3306
mallchat.mysql.db=mallchat
mallchat.mysql.username=root
mallchat.mysql.password=gyl808004
##################redis??##################
mallchat.redis.host=192.168.184.104
mallchat.redis.port=6379
mallchat.redis.password=123456
##################jwt##################
mallchat.jwt.secret=dsfsdfsdfsdfsd
##################???????##################
mallchat.wx.callback= http://3ee1180a.r7.cpolar.cn
mallchat.wx.appId=wxf4b5017c9ed7def6
mallchat.wx.secret=b7bdfaf10bb1b055e92c81b339b8e71a
# ??????Token?
mallchat.wx.token=sdfsf

# ??????EncodingAESKey?
mallchat.wx.aesKey=sha1
##################OSS??##################
oss.enabled=true
oss.type=minio
oss.endpoint=http://192.168.184.104:9000
oss.access-key=F0TGFJRA28W6E35ULMAZ
oss.secret-key=EPBeO8G5xfuExVwbBQrYezk7zaV9LUYFjpuRGQiS
oss.bucket-name=mallchat

rocketmq.name-server=192.168.184.104:9876
rocketmq.access-key=mallchat
rocketmq.secret-key=12345678
rocketmq.producer.send-message-timeout=60000
rocketmq.producer.retry-times-when-send-failed=10
rocketmq.producer.retry-next-server=true
##################gpt??##################
mallchat.chatgpt.use=true
mallchat.chatgpt.uid=10001
mallchat.chatgpt.key=81fa2fa9adce474da8c05b787caffd2a.JiNycdA8Xire5LeM
mallchat.chatgpt.proxyUrl=https://open.bigmodel.cn/api/paas/v4/chat/completions
mallchat.chatgpt.modelName=glm-4-flash-250414
mallchat.chatglm2.use=false
mallchat.chatglm2.url=http://v32134.cc
mallchat.chatglm2.uid=10002
